# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientadress',
            name='company',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientadress',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
