# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_deadline',
            field=models.DateField(verbose_name=datetime.date(2019, 4, 4)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='Common/static/media/'),
        ),
    ]
