# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20190329_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_deadline',
            field=models.DateField(verbose_name=datetime.date(2019, 4, 6)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/'),
        ),
    ]
